# Generated by Django 5.2.6 on 2025-11-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.IntegerField(default=20)),
                ("height", models.IntegerField(default=20)),
                ("author", models.CharField(blank=True, max_length=30)),
                ("food_count", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("board_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("author", models.CharField(blank=True, max_length=30)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("greediness", models.FloatField(default=0.5)),
                ("caution", models.FloatField(default=0.5)),
                ("direction_bias", models.FloatField(default=0.0)),
                ("circliness", models.FloatField(default=0.5)),
                ("chaos", models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winner", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(auto_now=True)),
                ("total_turns", models.PositiveIntegerField(default=0)),
                ("apples_a", models.PositiveIntegerField(default=0)),
                ("apples_b", models.PositiveIntegerField(default=0)),
                ("a_survival_time", models.PositiveIntegerField(default=0)),
                ("b_survival_time", models.PositiveIntegerField(default=0)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.board"
                    ),
                ),
                (
                    "bot1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot1_matches",
                        to="project.bot",
                    ),
                ),
                (
                    "bot2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot2_matches",
                        to="project.bot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_number", models.IntegerField()),
                ("bot1_move", models.CharField(max_length=5)),
                ("bot2_move", models.CharField(max_length=5)),
                ("bot1_head_x", models.IntegerField()),
                ("bot1_head_y", models.IntegerField()),
                ("bot2_head_x", models.IntegerField()),
                ("bot2_head_y", models.IntegerField()),
                ("apple_positions", models.JSONField()),
                ("bot1_ate", models.BooleanField(default=False)),
                ("bot2_ate", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_events",
                        to="project.match",
                    ),
                ),
            ],
        ),
    ]
