# Generated by Django 5.2.6 on 2025-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="color",
            field=models.CharField(default="#00FF00", max_length=7),
        ),
    ]
