# Generated by Django 5.2.6 on 2025-11-21 20:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_bot_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="color",
            field=colorfield.fields.ColorField(
                default="#00FF00", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
