# Generated by Django 5.2.6 on 2025-12-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_bot_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
