# Generated by Django 5.2.6 on 2025-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_board_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moveevent",
            name="bot1_head_x",
        ),
        migrations.RemoveField(
            model_name="moveevent",
            name="bot1_head_y",
        ),
        migrations.RemoveField(
            model_name="moveevent",
            name="bot2_head_x",
        ),
        migrations.RemoveField(
            model_name="moveevent",
            name="bot2_head_y",
        ),
        migrations.AddField(
            model_name="bot",
            name="introversion",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="moveevent",
            name="bot1_body",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moveevent",
            name="bot2_body",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
