# Generated by Django 5.2.6 on 2025-12-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_remove_moveevent_bot1_head_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveevent",
            name="bot1_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="moveevent",
            name="bot2_alive",
            field=models.BooleanField(default=True),
        ),
    ]
