# Generated by Django 5.2.6 on 2025-12-09 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_moveevent_bot1_alive_moveevent_bot2_alive"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotBoardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("avg_turns", models.FloatField(default=0.0)),
                ("avg_apples", models.FloatField(default=0.0)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.board"
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.bot"
                    ),
                ),
            ],
        ),
    ]
