# Generated by Django 5.2.6 on 2025-12-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_botboardstats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="author",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="author",
        ),
    ]
