# Generated by Django 5.2.6 on 2025-12-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_remove_board_author_remove_bot_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="color",
            field=models.CharField(default="#00ff00", max_length=7),
        ),
    ]
